package landing

import (
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net"
	"net/url"
	"strconv"
	"strings"
)

// ClashProxyYAML converts a single proxy URI into a Clash/Mihomo proxy list
// item. name overrides the URI's own display name when non-empty. Unsupported
// schemes (socks5, naive, mieru, snell, …) return ok=false so callers can keep
// them in the URI list but omit them from the YAML profile.
func ClashProxyYAML(uri, name string) (string, bool) {
	uri = strings.TrimSpace(uri)
	if uri == "" {
		return "", false
	}
	if name == "" {
		if n, ok := parseOne(uri); ok {
			name = n.Name
		}
	}
	if name == "" {
		name = "proxy"
	}
	idx := strings.Index(uri, "://")
	if idx <= 0 {
		return "", false
	}
	switch strings.ToLower(uri[:idx]) {
	case "ss":
		return clashSS(uri, name)
	case "vmess":
		return clashVMess(uri, name)
	case "vless":
		return clashVLESS(uri, name)
	case "trojan":
		return clashTrojan(uri, name)
	case "hy2", "hysteria2":
		return clashHy2(uri, name)
	case "socks5", "socks5h", "socks":
		return clashSocks5(uri, name)
	default:
		return "", false
	}
}

// NamedURI is a display name paired with a proxy URI for profile assembly.
type NamedURI struct {
	Name string
	URI  string
}

// ClashProfile assembles a pullable Clash Verge / Mihomo profile: one select
// group over every convertible proxy, MATCH → that group. Items that cannot
// become YAML are skipped; an empty proxy list still yields a valid file.
func ClashProfile(items []NamedURI) string {
	var blocks []string
	var names []string
	for _, it := range items {
		y, ok := ClashProxyYAML(it.URI, it.Name)
		if !ok {
			continue
		}
		blocks = append(blocks, y)
		names = append(names, it.Name)
	}
	var b strings.Builder
	b.WriteString("# generated by nft — Clash Verge / Mihomo\n")
	b.WriteString("mixed-port: 7890\n")
	b.WriteString("allow-lan: false\n")
	b.WriteString("mode: rule\n")
	b.WriteString("log-level: info\n")
	b.WriteString("ipv6: true\n")
	b.WriteString("unified-delay: true\n")
	b.WriteString("dns:\n")
	b.WriteString("  enable: true\n")
	b.WriteString("  enhanced-mode: fake-ip\n")
	b.WriteString("  nameserver:\n")
	b.WriteString("    - 8.8.8.8\n")
	b.WriteString("    - 1.1.1.1\n")
	b.WriteString("proxies:\n")
	if len(blocks) == 0 {
		b.WriteString("  []\n")
	} else {
		for _, block := range blocks {
			b.WriteString(indentClashBlock(block))
			b.WriteByte('\n')
		}
	}
	b.WriteString("proxy-groups:\n")
	b.WriteString("  - name: PROXY\n")
	b.WriteString("    type: select\n")
	b.WriteString("    proxies:\n")
	if len(names) == 0 {
		b.WriteString("      - DIRECT\n")
	} else {
		for _, n := range names {
			b.WriteString("      - ")
			b.WriteString(yamlQuoted(n))
			b.WriteByte('\n')
		}
		b.WriteString("      - DIRECT\n")
	}
	b.WriteString("rules:\n")
	b.WriteString("  - MATCH,PROXY\n")
	return b.String()
}

func indentClashBlock(block string) string {
	lines := strings.Split(strings.TrimRight(block, "\n"), "\n")
	var b strings.Builder
	for i, line := range lines {
		if i > 0 {
			b.WriteByte('\n')
		}
		b.WriteString("  ")
		b.WriteString(line)
	}
	return b.String()
}

func clashSS(uri, name string) (string, bool) {
	rest := uri[len("ss://"):]
	if h := strings.Index(rest, "#"); h >= 0 {
		rest = rest[:h]
	}
	plugin, pluginOpts := "", ""
	if q := strings.Index(rest, "?"); q >= 0 {
		params := parseQuery(rest[q+1:])
		plugin = params["plugin"]
		pluginOpts = params["plugin-opts"]
		rest = rest[:q]
	}
	var method, password, host string
	var port int
	if at := strings.LastIndex(rest, "@"); at >= 0 {
		userinfo := rest[:at]
		if dec, ok := b64Decode(userinfo); ok && strings.Contains(string(dec), ":") {
			userinfo = string(dec)
		}
		colon := strings.Index(userinfo, ":")
		if colon < 0 {
			return "", false
		}
		method, password = userinfo[:colon], userinfo[colon+1:]
		h, p, ok := splitHP(rest[at+1:])
		if !ok {
			return "", false
		}
		host, port = h, p
	} else {
		dec, ok := b64Decode(rest)
		if !ok {
			return "", false
		}
		s := string(dec)
		at := strings.LastIndex(s, "@")
		if at < 0 {
			return "", false
		}
		colon := strings.Index(s[:at], ":")
		if colon < 0 {
			return "", false
		}
		method, password = s[:colon], s[colon+1:at]
		h, p, ok := splitHP(s[at+1:])
		if !ok {
			return "", false
		}
		host, port = h, p
	}
	L := []string{
		fmt.Sprintf("- name: %s", yamlQuoted(name)),
		"  type: ss",
		fmt.Sprintf("  server: %s", yamlScalar(host)),
		fmt.Sprintf("  port: %d", port),
		fmt.Sprintf("  cipher: %s", yamlScalar(method)),
		fmt.Sprintf("  password: %s", yamlQuoted(password)),
		"  udp: true",
	}
	if plugin != "" {
		L = append(L, "  plugin: "+yamlScalar(plugin))
		if pluginOpts != "" {
			L = append(L, "  plugin-opts: "+yamlQuoted(pluginOpts))
		}
	}
	return strings.Join(L, "\n"), true
}

func clashVMess(uri, name string) (string, bool) {
	dec, ok := b64Decode(strings.TrimPrefix(uri, "vmess://"))
	if !ok {
		return "", false
	}
	var m map[string]any
	if err := json.Unmarshal(dec, &m); err != nil {
		return "", false
	}
	host, _ := m["add"].(string)
	port := jsonPort(m["port"])
	uuid, _ := m["id"].(string)
	if host == "" || port < 1 || uuid == "" {
		return "", false
	}
	aid := 0
	if v := jsonPort(m["aid"]); v > 0 {
		aid = v
	}
	cipher, _ := m["scy"].(string)
	if cipher == "" {
		cipher = "auto"
	}
	netw, _ := m["net"].(string)
	if netw == "" {
		netw = "tcp"
	}
	L := []string{
		fmt.Sprintf("- name: %s", yamlQuoted(name)),
		"  type: vmess",
		fmt.Sprintf("  server: %s", yamlScalar(host)),
		fmt.Sprintf("  port: %d", port),
		fmt.Sprintf("  uuid: %s", yamlScalar(uuid)),
		fmt.Sprintf("  alterId: %d", aid),
		fmt.Sprintf("  cipher: %s", yamlScalar(cipher)),
	}
	if netw != "tcp" {
		L = append(L, "  network: "+yamlScalar(netw))
	}
	if tls, _ := m["tls"].(string); tls == "tls" {
		L = append(L, "  tls: true")
	}
	if sni, _ := m["sni"].(string); sni != "" {
		L = append(L, "  servername: "+yamlScalar(sni))
	}
	if netw == "ws" {
		L = append(L, "  ws-opts:")
		if path, _ := m["path"].(string); path != "" {
			L = append(L, fmt.Sprintf("    path: %s", yamlQuoted(path)))
		}
		if h, _ := m["host"].(string); h != "" {
			L = append(L, "    headers:", "      Host: "+yamlScalar(h))
		}
	} else if netw == "grpc" {
		if path, _ := m["path"].(string); path != "" {
			L = append(L, "  grpc-opts:", fmt.Sprintf("    grpc-service-name: %s", yamlQuoted(path)))
		}
	}
	L = append(L, "  udp: true")
	return strings.Join(L, "\n"), true
}

func clashVLESS(uri, name string) (string, bool) {
	u, err := url.Parse(uri)
	if err != nil || u.User == nil {
		return "", false
	}
	host := u.Hostname()
	port, _ := strconv.Atoi(u.Port())
	uuid := u.User.Username()
	if host == "" || port < 1 || uuid == "" {
		return "", false
	}
	q := u.Query()
	L := []string{
		fmt.Sprintf("- name: %s", yamlQuoted(name)),
		"  type: vless",
		fmt.Sprintf("  server: %s", yamlScalar(host)),
		fmt.Sprintf("  port: %d", port),
		fmt.Sprintf("  uuid: %s", yamlScalar(uuid)),
	}
	if flow := q.Get("flow"); flow != "" {
		L = append(L, "  flow: "+yamlScalar(flow))
	}
	sec := q.Get("security")
	if sec == "tls" || sec == "reality" {
		L = append(L, "  tls: true")
	}
	if sni := firstNonEmpty(q.Get("sni"), q.Get("servername")); sni != "" {
		L = append(L, "  servername: "+yamlScalar(sni))
	}
	if fp := q.Get("fp"); fp != "" {
		L = append(L, "  client-fingerprint: "+yamlScalar(fp))
	}
	if sec == "reality" {
		L = append(L, "  reality-opts:")
		if pbk := q.Get("pbk"); pbk != "" {
			L = append(L, "    public-key: "+yamlScalar(pbk))
		}
		if sid := q.Get("sid"); sid != "" {
			L = append(L, "    short-id: "+yamlScalar(sid))
		}
	}
	netw := q.Get("type")
	if netw == "" {
		netw = "tcp"
	}
	if netw != "tcp" {
		L = append(L, "  network: "+yamlScalar(netw))
	}
	L = appendTransport(L, netw, q)
	L = append(L, "  udp: true")
	return strings.Join(L, "\n"), true
}

func clashTrojan(uri, name string) (string, bool) {
	u, err := url.Parse(uri)
	if err != nil || u.User == nil {
		return "", false
	}
	host := u.Hostname()
	port, _ := strconv.Atoi(u.Port())
	password, _ := u.User.Password()
	if password == "" {
		password = u.User.Username()
	}
	if host == "" || port < 1 || password == "" {
		return "", false
	}
	q := u.Query()
	L := []string{
		fmt.Sprintf("- name: %s", yamlQuoted(name)),
		"  type: trojan",
		fmt.Sprintf("  server: %s", yamlScalar(host)),
		fmt.Sprintf("  port: %d", port),
		fmt.Sprintf("  password: %s", yamlQuoted(password)),
	}
	if sni := firstNonEmpty(q.Get("sni"), q.Get("peer")); sni != "" {
		L = append(L, "  sni: "+yamlScalar(sni))
	}
	if fp := q.Get("fp"); fp != "" {
		L = append(L, "  client-fingerprint: "+yamlScalar(fp))
	}
	netw := q.Get("type")
	if netw == "" {
		netw = "tcp"
	}
	if netw != "tcp" {
		L = append(L, "  network: "+yamlScalar(netw))
	}
	L = appendTransport(L, netw, q)
	L = append(L, "  udp: true")
	return strings.Join(L, "\n"), true
}

func clashSocks5(uri, name string) (string, bool) {
	u, err := url.Parse(uri)
	if err != nil {
		return "", false
	}
	host := u.Hostname()
	port, _ := strconv.Atoi(u.Port())
	if host == "" || port < 1 {
		return "", false
	}
	L := []string{
		fmt.Sprintf("- name: %s", yamlQuoted(name)),
		"  type: socks5",
		fmt.Sprintf("  server: %s", yamlScalar(host)),
		fmt.Sprintf("  port: %d", port),
	}
	if u.User != nil {
		if user := u.User.Username(); user != "" {
			L = append(L, "  username: "+yamlQuoted(user))
		}
		if pass, ok := u.User.Password(); ok && pass != "" {
			L = append(L, "  password: "+yamlQuoted(pass))
		}
	}
	L = append(L, "  udp: true")
	return strings.Join(L, "\n"), true
}

func clashHy2(uri, name string) (string, bool) {
	u, err := url.Parse(uri)
	if err != nil {
		return "", false
	}
	host := u.Hostname()
	port, _ := strconv.Atoi(u.Port())
	if host == "" || port < 1 {
		return "", false
	}
	auth := ""
	if u.User != nil {
		auth = u.User.Username()
		if p, ok := u.User.Password(); ok && p != "" {
			auth = p
		}
	}
	q := u.Query()
	L := []string{
		fmt.Sprintf("- name: %s", yamlQuoted(name)),
		"  type: hysteria2",
		fmt.Sprintf("  server: %s", yamlScalar(host)),
		fmt.Sprintf("  port: %d", port),
	}
	if auth != "" {
		L = append(L, "  password: "+yamlQuoted(auth))
	}
	if sni := q.Get("sni"); sni != "" {
		L = append(L, "  sni: "+yamlScalar(sni))
	}
	if q.Get("insecure") == "1" {
		L = append(L, "  skip-cert-verify: true")
	}
	if q.Get("obfs") == "salamander" && q.Get("obfs-password") != "" {
		L = append(L, "  obfs: salamander")
		L = append(L, "  obfs-password: "+yamlQuoted(q.Get("obfs-password")))
	}
	return strings.Join(L, "\n"), true
}

func appendTransport(L []string, netw string, q url.Values) []string {
	if netw == "ws" {
		L = append(L, "  ws-opts:")
		if path := q.Get("path"); path != "" {
			L = append(L, "    path: "+yamlQuoted(path))
		}
		if host := q.Get("host"); host != "" {
			L = append(L, "    headers:", "      Host: "+yamlScalar(host))
		}
	} else if netw == "grpc" {
		svc := firstNonEmpty(q.Get("serviceName"), q.Get("service_name"))
		if svc != "" {
			L = append(L, "  grpc-opts:", "    grpc-service-name: "+yamlQuoted(svc))
		}
	}
	return L
}

func parseQuery(raw string) map[string]string {
	m := map[string]string{}
	for _, p := range strings.Split(raw, "&") {
		if p == "" {
			continue
		}
		k, v, _ := strings.Cut(p, "=")
		if k == "" {
			continue
		}
		dk, _ := url.QueryUnescape(k)
		dv, _ := url.QueryUnescape(v)
		m[dk] = dv
	}
	return m
}

func splitHP(s string) (string, int, bool) {
	s = strings.TrimSpace(s)
	if s == "" {
		return "", 0, false
	}
	host, portStr, err := net.SplitHostPort(s)
	if err != nil {
		return "", 0, false
	}
	port, err := strconv.Atoi(portStr)
	if err != nil || host == "" || port < 1 || port > 65535 {
		return "", 0, false
	}
	return host, port, true
}

func yamlQuoted(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	return `"` + s + `"`
}

func yamlScalar(s string) string {
	if s == "" || strings.ContainsAny(s, ":#{}[],&*?|>!%@`'\" \t") {
		return yamlQuoted(s)
	}
	return s
}

func firstNonEmpty(vals ...string) string {
	for _, v := range vals {
		if v != "" {
			return v
		}
	}
	return ""
}

// EncodeURISubscription is the standard client subscription body: a
// newline-joined URI list, then standard base64 (with padding).
func EncodeURISubscription(uris []string) string {
	var lines []string
	for _, u := range uris {
		u = strings.TrimSpace(u)
		if u != "" {
			lines = append(lines, u)
		}
	}
	raw := strings.Join(lines, "\n")
	if raw != "" {
		raw += "\n"
	}
	return base64.StdEncoding.EncodeToString([]byte(raw))
}
